### ISSUE TITLE
getMotionIds() doesn't handle motions in nested namespaces 

### ISSUE THREAD

**Issue by v-lopez** [pal-robotics/play_motion#23]
Given the following parameters in the param server:

```
play_motion:
  motions:
    alive_engine:
      backwards_1:
        joints: []
          ....
    wave:
      joints: []  
```

getMotionIds() will return [alive_engine, wave]. But alive_engine is not a motion, but a namespace that contains other motions. 

I believe it should:
1. Check that what it has found is a motion (ie it has joints, points, etc..)
2. If it is not a motion, look for motions nested within it.
